# Generated by Django 3.1.2 on 2020-12-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_incident', models.CharField(default='', max_length=255, null=True)),
                ('contact_name', models.CharField(default='', max_length=255, null=True)),
                ('contact_number', models.CharField(default='', max_length=255, null=True)),
                ('insurer', models.CharField(default='', max_length=255, null=True)),
                ('ticket_type', models.CharField(default='', max_length=255, null=True)),
                ('ticket_status', models.CharField(default='', max_length=255, null=True)),
                ('vehicle_reg_num', models.CharField(default='', max_length=255, null=True)),
                ('vehicle_manufacturer', models.CharField(default='', max_length=255, null=True)),
                ('vehicle_model', models.CharField(default='', max_length=255, null=True)),
                ('assigned_to', models.CharField(default='', max_length=255, null=True)),
                ('tow_from', models.CharField(default='', max_length=255, null=True)),
                ('tow_to_workshop', models.CharField(default='', max_length=255, null=True)),
                ('tow_to_address', models.CharField(default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
    ]
