# Generated by Django 3.1.2 on 2020-12-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20201217_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='lng',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='zipcode',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
