# Generated by Django 3.1.2 on 2020-12-27 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_towtoworkshop_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='assigned_to',
            new_name='bookie',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='contact_name',
            new_name='connections',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='contact_number',
            new_name='expire',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='date_of_incident',
            new_name='license_key',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='insurer',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='locationID',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='ticket_status',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='ticket_type',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='tow_from',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='tow_to_address',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='tow_to_workshop',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='vehicle_manufacturer',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='vehicle_model',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='vehicle_reg_num',
        ),
    ]
