# Generated by Django 3.1.2 on 2020-12-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20201227_1422'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='TowToWorkshop',
        ),
        migrations.DeleteModel(
            name='VehicleManufacturer',
        ),
        migrations.AddField(
            model_name='tickets',
            name='status',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
