# Generated by Django 3.1.2 on 2021-01-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_auto_20201227_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploadedcsv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(default='', max_length=255, null=True)),
                ('filename', models.FileField(default='', null=True, upload_to='csv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'uploadedcsv',
            },
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
    ]
