# Generated by Django 3.1.2 on 2021-01-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_auto_20210113_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedcsv',
            name='file',
            field=models.FileField(default='', null=True, upload_to='csv'),
        ),
        migrations.AlterField(
            model_name='uploadedcsv',
            name='filename',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
