# Generated by Django 3.1.2 on 2021-01-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_auto_20210113_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploadedpdb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(default='', max_length=255, null=True)),
                ('filename', models.CharField(default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'uploadedpdb',
            },
        ),
    ]
